export const studyMock = [
  {
    id: "study_1",
    password: "a1234",
    nickname: "스프린트",
    title: "하루 1시간 코딩 스터디",
    description: "매일 조금씩 꾸준히 코딩 공부하기 위한 스터디입니다.",
    points: 310,
    bg: 1,
    habits: [
      {
        id: "habit_1_1",
        title: "30분 이상 알고리즘 문제 풀기",
        checkedDays: {
          월: true,
          화: false,
          수: true,
          목: false,
          금: true,
          토: false,
          일: true,
        },
      },
      {
        id: "habit_1_2",
        title: "CS 지식 블로그 정리하기",
        checkedDays: {
          월: false,
          화: true,
          수: true,
          목: false,
          금: false,
          토: true,
          일: false,
        },
      },
    ],
    emojis: [
      { emoji: "🔥", count: 5 },
      { emoji: "👏", count: 2 },
    ],
    createdAt: "2025-06-13T12:00:00Z",
    createdBy: "user_abc123",
  },
  {
    id: "study_2",
    password: "a2345",
    nickname: "이유디",
    title: "아침 루틴 챌린지",
    description: "건강한 하루를 위한 아침 습관 만들기 챌린지입니다.",
    points: 240,
    bg: 5,
    habits: [
      {
        id: "habit_2_1",
        title: "일어나서 바로 물 한 잔 마시기",
        checkedDays: {
          월: true,
          화: true,
          수: true,
          목: true,
          금: true,
          토: true,
          일: true,
        },
      },
      {
        id: "habit_2_2",
        title: "10분 스트레칭",
        checkedDays: {
          월: false,
          화: true,
          수: false,
          목: true,
          금: false,
          토: true,
          일: false,
        },
      },
      {
        id: "habit_2_3",
        title: "명상 5분",
        checkedDays: {
          월: true,
          화: false,
          수: false,
          목: true,
          금: true,
          토: false,
          일: true,
        },
      },
    ],
    emojis: [
      { emoji: "🌞", count: 3 },
      { emoji: "💖", count: 1 },
      { emoji: "💪", count: 4 },
    ],
    createdAt: "2025-06-12T08:30:00Z",
    createdBy: "user_def456",
  },
  {
    id: "study_3",
    password: "a3456",
    nickname: "밀리",
    title: "책 읽는 밤",
    description: "매일 자기 전 20분 독서하기 스터디입니다.",
    points: 150,
    bg: 3,
    habits: [
      {
        id: "habit_3_1",
        title: "잠들기 전 독서 20분",
        checkedDays: {
          월: true,
          화: true,
          수: true,
          목: true,
          금: true,
          토: false,
          일: false,
        },
      },
    ],
    emojis: [
      { emoji: "📚", count: 6 },
      { emoji: "🛏️", count: 2 },
      { emoji: "😴", count: 1 },
    ],
    createdAt: "2025-06-11T22:15:00Z",
    createdBy: "user_xyz789",
  },
  {
    id: "study_4",
    password: "a4567",
    nickname: "루틴러버",
    title: "기상 후 루틴 챌린지",
    description: "기분 좋은 하루를 위한 아침 루틴 만들기 도전!",
    points: 180,
    bg: 2,
    habits: [
      {
        id: "habit_4_1",
        title: "기상 후 스트레칭 5분",
        checkedDays: {
          월: true,
          화: true,
          수: false,
          목: true,
          금: false,
          토: true,
          일: false,
        },
      },
      {
        id: "habit_4_2",
        title: "아침 일기 쓰기",
        checkedDays: {
          월: false,
          화: false,
          수: true,
          목: true,
          금: true,
          토: false,
          일: true,
        },
      },
    ],
    emojis: [
      { emoji: "🌅", count: 4 },
      { emoji: "📝", count: 2 },
    ],
    createdAt: "2025-06-10T06:45:00Z",
    createdBy: "user_morn123",
  },
  {
    id: "study_5",
    password: "a5678",
    nickname: "헬시조",
    title: "건강 루틴 챌린지",
    description: "작은 습관으로 건강한 일상 만들기!",
    points: 275,
    bg: 4,
    habits: [
      {
        id: "habit_5_1",
        title: "매일 물 1.5L 마시기",
        checkedDays: {
          월: true,
          화: true,
          수: true,
          목: true,
          금: true,
          토: true,
          일: true,
        },
      },
      {
        id: "habit_5_2",
        title: "저녁 7시 이후 금식",
        checkedDays: {
          월: false,
          화: true,
          수: false,
          목: true,
          금: false,
          토: false,
          일: true,
        },
      },
    ],
    emojis: [
      { emoji: "💧", count: 3 },
      { emoji: "🥗", count: 2 },
      { emoji: "💪", count: 2 },
    ],
    createdAt: "2025-06-09T18:00:00Z",
    createdBy: "user_fitlife",
  },
  {
    id: "study_6",
    password: "a6789",
    nickname: "코딩토끼",
    title: "주말 알고리즘 도장깨기",
    description: "주말을 활용해 알고리즘 실력을 키워요!",
    points: 330,
    bg: 1,
    habits: [
      {
        id: "habit_6_1",
        title: "1시간 이상 알고리즘 풀기",
        checkedDays: {
          월: false,
          화: false,
          수: false,
          목: false,
          금: false,
          토: true,
          일: true,
        },
      },
      {
        id: "habit_6_2",
        title: "풀이 블로그 포스팅",
        checkedDays: {
          월: false,
          화: false,
          수: false,
          목: false,
          금: false,
          토: true,
          일: false,
        },
      },
    ],
    emojis: [
      { emoji: "🐰", count: 4 },
      { emoji: "🧠", count: 3 },
    ],
    createdAt: "2025-06-08T14:00:00Z",
    createdBy: "user_algo88",
  },
  {
    id: "study_7",
    password: "a7890",
    nickname: "나잇루틴",
    title: "야근 후에도 지키는 자기관리",
    description: "바쁜 일상 속에서도 저녁 루틴을 지켜요.",
    points: 220,
    bg: 6,
    habits: [
      {
        id: "habit_7_1",
        title: "퇴근 후 산책 15분",
        checkedDays: {
          월: true,
          화: true,
          수: true,
          목: false,
          금: false,
          토: false,
          일: false,
        },
      },
      {
        id: "habit_7_2",
        title: "취침 전 휴대폰 없이 10분 명상",
        checkedDays: {
          월: false,
          화: true,
          수: true,
          목: false,
          금: true,
          토: false,
          일: false,
        },
      },
    ],
    emojis: [
      { emoji: "🌙", count: 3 },
      { emoji: "😌", count: 2 },
      { emoji: "🚶‍♀️", count: 1 },
    ],
    createdAt: "2025-06-07T23:10:00Z",
    createdBy: "user_nightowl",
  },
];
